line-length = 100
target-version = "py312"

[lint]
select = ["E", "F", "W", "I", "UP", "B", "SIM", "C4", "BLE", "RUF"]
ignore = ["E501", "RUF001", "RUF002", "RUF003", "B008"]

[lint.per-file-ignores]
"migrations/*" = ["I001"]
